version: '3'

volumes:
  postgres_volume:
  prometheus_data:

services:
  postgres:
    image: postgres:14.7-alpine3.17
    environment:
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
      - "POSTGRES_DB=${PG_DB}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

#   workaound on ubuntu
    extra_hosts:
      - "host.docker.internal:host-gateway"